In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_53.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_62.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_56.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_71.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_15.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_99.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_80.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_42.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_26.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_21.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_9.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_57.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_93.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_8.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_87.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_35.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_77.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_2.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_95.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_28.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_63.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_60.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_37.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_23.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_5.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_46.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_85.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_11.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_39.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_59.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_84.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_61.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_81.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_89.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_47.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_76.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_100.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_94.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_27.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_22.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_4.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_29.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_88.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_7.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_54.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_14.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_72.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_13.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_69.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_51.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_41.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_30.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_90.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_16.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_68.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_92.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/SAP Developer resumes/Image_3.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/75.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/137.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/102.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/23.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/d0479872162b5b64.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/73.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/6c312128798f9b6f.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/41.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/25.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/31.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/45.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/98.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/127.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/120.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/111.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/30.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/118.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/49.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/24.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/57740c125a5f9af5.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/2fd974489b2980ea.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/63.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/36.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/15.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/e5c54c927da55a4b.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/89.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/5.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/93.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/56.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/122.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/3a3b1c9b89581b02.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/29.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/8.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/86.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/7f33f3ce88e4436c.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/0.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/116.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/08e79fd62868f24a.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/103.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/14.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/5e53a391a11ad3ea.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/17.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/775ddcf1ac59717b.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/2889e6a96bf64411.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/0b3f391fe4e5c756.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/138.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/27.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/135.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/77.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/08c17b29832594aa.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/114.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/20.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/81.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/58.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/55.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/39.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/133.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/130.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/26.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/123.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/aa67a959d23c057d.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/f032d6a5da28be32.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/c29858429d983003.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/121.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/81cd683113e725e8.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/79.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/64.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/134.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/95.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/91.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/38.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/44c4c8cf94018ce7.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/9aa301972e8a2984.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/12.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/9.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/7.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/47.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/119.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/40.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/5c703201a48e1235.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/66.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/4.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/864293e9c26c30b9.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/74.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/78.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/54.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/f6ae185c0e682454.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/44.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/108.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/19.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/b0697b0856ad56ba.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/628972d26fac7ade.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/100.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/edd9e704c9ea0b08.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/6.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/53.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/99.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/94.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/30eccac48cf78647.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/97.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/61.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/110.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/34.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/1.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/42.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/96.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/88.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/136.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/80.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/10.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/105.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/60.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/22.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/117.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/21.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/edfba17945e11237.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/48.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/51.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/f0a8ce4949bd9bb3.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/59.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/32.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/28.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/113.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/68.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/129.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/856cc456294ed92c.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/65.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/33.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/109.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/124.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/61fc158e79b70010.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/f952a74f4f76618b.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/87.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/76.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/3c07907dd3698f69.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/b8b7849de3dad95b.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/72.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/132.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/85.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/112.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/57.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/2e1a56ae67f6520e.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/13.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/46.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/126.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/101.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/e20721a5132f7b6c.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/3980b122c8748a68.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/106.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/69.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/84.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/67.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/06792a43f7feb017.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/16.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/97fa94d4bfae2b6f.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/eef46cd1f465b2d0.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/82.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/107.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/115.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/35.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/11.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/5218e5a9d49f622d.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/70.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/83.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/50.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/125.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/71.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/128.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/52.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/92.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/0733c547e25f07f6.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/438fc23473242e83.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/3.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/131.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/3daaa76e5ed301e3.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/2.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/104.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/eb4f2a7957df7e09.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/5c46415022c426bb.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/90.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/6fba9302753277c0.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/b0fa55acaedeb392.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/43.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/37.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/62.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Database/18.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Civil Engineer resumes/Image_53.pdf
/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF/Civil Engineer resumes/Image_62.pdf

In [2]:
# cell 1
!pip install -q sentence-transformers pdfplumber pytesseract pdf2image pypdf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.4/68.4 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 87.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 68.7 MB/s eta 0:00:00:00:01

In [3]:
# cell 2
!apt-get update -qq
!apt-get install -y poppler-utils tesseract-ocr

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 103 not upgraded.
Need to get 186 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12 [186 kB]
Fetched 186 kB in 0s (4,135 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 120968 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.12_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.12) ...
Setting up poppler-utils (22.02.0-2ubuntu0.12) ...
Processing triggers for man-db (2.10.2-1) ...

In [4]:
# cell 3
import os
import pandas as pd
import numpy as np

from pypdf import PdfReader
import pdfplumber
import pytesseract
from pdf2image import convert_from_path

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
#cell 4
resume_folder = "/kaggle/input/datasets/hadikp/resume-data-pdf/Resumes PDF"

print("Exists:", os.path.exists(resume_folder))

Exists: True

In [6]:
#cell 5
import os

def extract_text_from_pdf(pdf_path):

    text = ""

    try:

        with pdfplumber.open(pdf_path) as pdf:

            for page in pdf.pages:

                extracted = page.extract_text()

                if extracted:
                    text += extracted + " "

        if len(text.strip()) < 50:

            images = convert_from_path(pdf_path)

            for image in images:

                text += pytesseract.image_to_string(image)

    except Exception as e:

        print("Error:", pdf_path, e)

    return text

import re

import re

def extract_candidate_name(text, fallback):

    if not text:
        return fallback

    bad_words = {
        "resume",
        "curriculum vitae",
        "experience",
        "objective",
        "profile",
        "professional summary",
        "development tools",
        "education",
        "skills",
        "email",
        "phone",
        "contact"
    }

    lines = text.split("\n")

    for line in lines[:20]:

        line = line.strip()

        if len(line) < 3 or len(line) > 40:
            continue

        lower = line.lower()

        if any(word in lower for word in bad_words):
            continue

        if "@" in line:
            continue

        if any(ch.isdigit() for ch in line):
            continue

        words = line.split()

        if 2 <= len(words) <= 4:
            return line.title()

    return fallback

In [7]:
# cell 6
resume_data = []

candidate_id = 1
limit = 50

for root, dirs, files in os.walk(resume_folder):

    for file in files:

        if candidate_id > limit:
            break

        if file.lower().endswith(".pdf"):

            path = os.path.join(root, file)

            text = extract_text_from_pdf(path)

            resume_data.append({
                "candidate_id": candidate_id,
                "candidate_name": extract_candidate_name(text,
file.replace(".pdf", "")
),
                "resume_text": text
            })

            candidate_id += 1

    if candidate_id > limit:
        break

print("Loaded:", len(resume_data))

Loaded: 50

In [8]:
# cell 7
df = pd.DataFrame(resume_data)

print(df.shape)

df.head()

(50, 3)

,candidate_id,candidate_name,resume_text
0,1,Key Results Areas:,we\n\nKey Results Areas:\n‘© Monttoring the ge...
1,2,Noah Ferry,EXPERIENCE\n11/2019 — present\n\n06/2017 — 08/...
2,3,Robert Smith,\n\nROBERT SMITH\n\nSap Abap Developer III\ni...
3,4,Lydia Botsford,EXPERIENCE\n\nEDUCATION\n\nSKILLS\n\nLydia Bot...
4,5,Kevin Graham,KEVIN GRAHAM\n\nIT/SAP PROFESSIONAL\n\n= 0 9 i...

In [114]:
# cell 8
job_description = """
Human Resources Manager

Skills:
Recruitment
Payroll
Employee Relations
Performance Management
Talent Acquisition
HR Policies
"""

In [115]:
# cell 9
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [126]:
# cell 10
resume_embeddings = model.encode(
    df["resume_text"].tolist(),
    show_progress_bar=True
)

jd_embedding = model.encode(job_description)

scores = cosine_similarity(
    [jd_embedding],
    resume_embeddings
)[0]

df["semantic_score"] = scores * 100

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

In [127]:
# cell 11
skills_list = [
    "python",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "nlp",
    "sql",
    "aws",
    "docker",
    "git",
    "java",
    "excel",
    "power bi",
    "data analysis"
]

In [128]:
# cell 12
def extract_skills(text):

    text = str(text).lower()

    return [
        skill
        for skill in skills_list
        if skill in text
    ]

In [129]:
# cell 13
jd_skills = extract_skills(job_description)

df["matched_skills"] = df["resume_text"].apply(extract_skills)

df["skill_score"] = (
    df["matched_skills"]
    .apply(lambda x: len(x))
    / max(len(jd_skills), 1)
) * 100

In [130]:
# Cell 14 - Hybrid Score

df["score"] = (
    0.8 * df["semantic_score"]
    + 0.2 * df["skill_score"]
)

print(df[["semantic_score", "skill_score", "score"]].head())

   semantic_score  skill_score      score
0       23.493668        300.0  78.794935
1       21.188303        300.0  76.950644
2       30.996572        200.0  64.797258
3       30.596245        200.0  64.476995
4       27.103065        200.0  61.682453

In [131]:
# Cell 15 - Recommendation

def get_recommendation(score):

    if score >= 75:
        return "Strong Fit"

    elif score >= 55:
        return "Good Fit"

    elif score >= 35:
        return "Potential Fit"

    else:
        return "Weak Fit"

df["recommendation"] = df["score"].apply(get_recommendation)

In [132]:
# cell 16
df["missing_or_weak_signals"] = df[
    "matched_skills"
].apply(
    lambda x: list(set(jd_skills) - set(x))
)

df["evidence"] = df["matched_skills"]

In [133]:
# cell 17
df = df.sort_values(
    "score",
    ascending=False
).reset_index(drop=True)

df["rank"] = df.index + 1

In [134]:
# cell 18
final_df = df[
    [
        "rank",
        "candidate_id",
        "candidate_name",
        "score",
        "recommendation",
        "matched_skills",
        "missing_or_weak_signals",
        "evidence"
    ]
]

final_df = final_df.copy()
final_df["score"] = final_df["score"].round(2)

final_df.head(20)

,rank,candidate_id,candidate_name,score,recommendation,matched_skills,missing_or_weak_signals,evidence
0,1,42,Image_29,78.79,Strong Fit,"[sql, excel, data analysis]",[],"[sql, excel, data analysis]"
1,2,22,Trinity Ankunding,76.95,Strong Fit,"[sql, java, excel]",[],"[sql, java, excel]"
2,3,15,Reilly Aufderhar,64.80,Good Fit,"[sql, excel]",[],"[sql, excel]"
3,4,2,Noah Ferry,64.48,Good Fit,"[java, excel]",[],"[java, excel]"
4,5,21,Kendal Deckow,61.68,Good Fit,"[sql, java]",[],"[sql, java]"
5,6,19,Jan Greenfelder,55.61,Good Fit,"[sql, git]",[],"[sql, git]"
6,7,45,Natalia Pfeffer,49.61,Potential Fit,[excel],[],[excel]
7,8,5,Kevin Graham,49.49,Potential Fit,[sql],[],[sql]
8,9,28,Adrian Penaloza,49.00,Potential Fit,[excel],[],[excel]
9,10,18,Anil Kumar Patra,48.53,Potential Fit,[excel],[],[excel]
10,11,10,Isadore Hilpert,46.87,Potential Fit,[excel],[],[excel]
11,12,11,Pete Auer,45.89,Potential Fit,[excel],[],[excel]
12,13,27,Wilburn Macejkovic,44.66,Potential Fit,[excel],[],[excel]
13,14,38,Rowan Mayer,44.06,Potential Fit,[excel],[],[excel]
14,15,7,Cayla Steuber,42.31,Potential Fit,[excel],[],[excel]
15,16,1,Key Results Areas:,41.61,Potential Fit,[excel],[],[excel]
16,17,37,Sap Hana Consultant,40.20,Potential Fit,[sql],[],[sql]
17,18,43,"Ewm, And Apo",39.91,Potential Fit,[sql],[],[sql]
18,19,30,Esther Jacobs,38.92,Potential Fit,[excel],[],[excel]
19,20,33,Abhishek Halder,38.75,Potential Fit,[excel],[],[excel]